version: '2'
services:

  database:
    container_name: wa-project-database
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_DB=waProject
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=123mudar
    volumes:
      - ./.data/postgresql:/var/lib/postgresql/data1
    ports:
      - "5432:5432"
    
  web:
    container_name: wa-project-api
    build: docker/dev
    ports:
      - "3001:3000"
      - "3229:9229"
    env_file:
      - .env
    volumes:
      - .:/server
    links:
      - database